export const ACTION_TYPE = {
	SET_FORUM_POST_DATA: 'SET_FORUM_POST_DATA',
	RESET_FORUM_POST_DATA: 'RESET_FORUM_POST_DATA',
	SET_SERVICE_DATA: 'SET_SERVICE_DATA',
	RESET_SERVICE_DATA: 'RESET_SERVICE_DATA',
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
};
