export const SERVICES = [
	{
		id: 1,
		title: 'Стрижка',
		description:
			'Профессиональный уход за шерстью питомца с учетом его породы и типа волос. Используем качественные инструменты и безопасные средства для стрижки. Гарантируем комфортное и бережное обращение с животным.',
		photo: 'https://i.pinimg.com/736x/ca/c7/55/cac7556c64ddafb3bec61f4585800c2b.jpg',
		serviceOwnerFirstName: 'Алексей',
		serviceOwnerLastName: 'Морозов',
		serviceOwnerPhoto: '/img/users/alexey.jpg',
		address: 'г. Москва, ул. Цветочная, 15',
		price: '1200 руб.',
		userEmail: 'alexey.morozov@example.com',
	},
	{
		id: 2,
		title: 'Груминг',
		description:
			'Комплексный уход за питомцем, включая стрижку, купание, чистку ушей и уход за когтями. Все процедуры проводятся в комфортных условиях, с использованием гипоаллергенных средств и специализированного оборудования.',
		photo: 'https://i.pinimg.com/736x/ca/c7/55/cac7556c64ddafb3bec61f4585800c2b.jpg',
		serviceOwnerFirstName: 'Елена',
		serviceOwnerLastName: 'Кузнецова',
		serviceOwnerPhoto: '/img/users/elena.jpg',
		address: 'г. Санкт-Петербург, пр. Невский, 45',
		price: '2500 руб.',
		userEmail: 'elena.kuznetsova@example.com',
	},
	{
		id: 3,
		title: 'Купание',
		description:
			'Щадящее купание с использованием специальных шампуней, подобранных под тип кожи и шерсти питомца. Включает массаж, сушку и укладку шерсти. Вода комфортной температуры, без стресса для животного.',
		photo: 'https://i.pinimg.com/736x/ca/c7/55/cac7556c64ddafb3bec61f4585800c2b.jpg',
		serviceOwnerFirstName: 'Михаил',
		serviceOwnerLastName: 'Сидоров',
		serviceOwnerPhoto: '/img/users/mikhail.jpg',
		address: 'г. Казань, ул. Пушкина, 10',
		price: '1800 руб.',
		userEmail: 'mikhail.sidorov@example.com',
	},
	{
		id: 4,
		title: 'Стрижка когтей',
		description:
			'Безопасное и безболезненное подстригание когтей, учитывающее анатомию лап питомца. Используем специальные ножницы и пилки, чтобы предотвратить расслоение когтей и дискомфорт при ходьбе.',
		photo: 'https://i.pinimg.com/736x/ca/c7/55/cac7556c64ddafb3bec61f4585800c2b.jpg',
		serviceOwnerFirstName: 'Сергей',
		serviceOwnerLastName: 'Волков',
		serviceOwnerPhoto: '/img/users/sergey.jpg',
		address: 'г. Новосибирск, ул. Лесная, 7',
		price: '900 руб.',
		userEmail: 'sergey.volkov@example.com',
	},
	{
		id: 5,
		title: 'Чистка ушей',
		description:
			'Деликатное очищение ушей питомца от серы и загрязнений, предотвращающее воспалительные процессы. Используем специальные лосьоны и стерильные инструменты для максимальной безопасности.',
		photo: 'https://i.pinimg.com/736x/ca/c7/55/cac7556c64ddafb3bec61f4585800c2b.jpg',
		serviceOwnerFirstName: 'Мария',
		serviceOwnerLastName: 'Белоусова',
		serviceOwnerPhoto: '/img/users/maria.jpg',
		address: 'г. Екатеринбург, пр. Ленина, 22',
		price: '700 руб.',
		userEmail: 'maria.belousova@example.com',
	},
	{
		id: 6,
		title: 'Консультация ветеринара',
		description:
			'Квалифицированная консультация по вопросам здоровья и ухода за питомцем. Врач проводит осмотр, даёт рекомендации по питанию, профилактике заболеваний и вакцинации.',
		photo: 'https://i.pinimg.com/736x/ca/c7/55/cac7556c64ddafb3bec61f4585800c2b.jpg',
		serviceOwnerFirstName: 'Иван',
		serviceOwnerLastName: 'Петров',
		serviceOwnerPhoto: '/img/users/ivan.jpg',
		address: 'г. Омск, ул. Советская, 3',
		price: '2000 руб.',
		userEmail: 'ivan.petrov@example.com',
	},
	{
		id: 7,
		title: 'Консультация кинолога',
		description:
			'Индивидуальная консультация с профессиональным кинологом, который поможет скорректировать поведение питомца, даст рекомендации по воспитанию и тренировкам. Учитываются особенности породы и характер животного.',
		photo: 'https://i.pinimg.com/736x/ca/c7/55/cac7556c64ddafb3bec61f4585800c2b.jpg',
		serviceOwnerFirstName: 'Анастасия',
		serviceOwnerLastName: 'Фролова',
		serviceOwnerPhoto: '/img/users/anastasia.jpg',
		address: 'г. Ростов-на-Дону, ул. Дружбы, 18',
		price: '3000 руб.',
		userEmail: 'anastasia.frolova@example.com',
	},
];
